# Generated by Django 4.2 on 2024-03-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary_app', '0003_textsection_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='textsection',
            name='text_translate',
            field=models.TextField(null=True),
        ),
    ]
