# Generated by Django 4.2 on 2024-03-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary_app', '0009_alter_author_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextTranslate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translated_text', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='textsection',
            name='text_translate',
        ),
    ]
